// import { MapKeysByDictionary } from '../dist/src/index.js';
const {
  MapKeysByDictionary,
} = require('../dist/map-keys-by-dictionary.cjs.js');
const { performance } = require('perf_hooks');
const util = require('util');

const demandsData = {
  totalCount: 322534,
  items: [
    {
      idContrat: '006004-PCL',
      categorie: {
        id: 2,
        code: 'AMS',
        nomCourt: 'AMS',
        nomLong: 'Adhésions Mouvement Santé',
      },
      dateCreation: '2021-03-02T16:11:44+0000',
      numGroupeAssure: '00-PS',
      dateEtat: '2021-03-03T11:00:15+0000',
      id: 1070791,
      nomAdherent: 'PRICCO',
      numInfinite: '15256357',
      isDeletedDemande: false,
      dateScan: '2021-03-02T16:11:44+0000',
      lotId: 120686,
      nbDocuments: 2,
      etat: 'Affectée',
      equipePersonneAffectee: {
        id: 6,
        code: 'ADHMOU',
        nomCourt: 'Adhésion Mouvement',
        nomLong: "POST'AIR - Adhésion Mouvement",
        adMapping: 'GT-0412',
      },
      codeER: '006',
      dateReception: '2018-02-28T00:00:00+0000',
      nbTacheEncours: 0,
      numAdhesion: '0000461477',
      idMnt: '11658220',
      isVIP: false,
      affectation: {
        personneAffectee: 'CHAREF Samia',
        dateAffectation: '2021-03-03T11:00:15+0000',
        equipePersonneAffectee: 6,
      },
      type: {
        id: 10,
        code: 'CADS',
        nomCourt: 'CHGTADMSAN',
        nomLong: 'Changement adresse / nom / RO - Santé',
        categorie: 2,
        readyState: 'À typer',
      },
      origine: {
        id: 4,
        code: 'PST',
        nomCourt: 'POSTAIR',
        nomLong: "Gestionnaire - Post'Air",
      },
      nbTacheTerminee: 1,
      isTestDemande: false,
      statut: 'Nouvelle',
    },
    {
      categorie: {
        id: 8,
        code: 'AMP',
        nomCourt: 'AMP',
        nomLong: 'Adhésions Mouvement Prévoyance',
      },
      dateCreation: '2018-03-01T10:37:23+0000',
      numGroupeAssure: '00-PS',
      dateEtat: '2021-03-11T18:04:06+0000',
      id: 28,
      nomAdherent: 'PRICCO',
      numInfinite: '15256357',
      isDeletedDemande: false,
      dateScan: '2018-03-01T10:40:20+0000',
      idContrat: '006004-PCL',
      prenomAdherent: 'PIERRE ERIC',
      lotId: 3,
      nbDocuments: 1,
      etat: 'Affectée',
      equipePersonneAffectee: {
        id: 6,
        code: 'ADHMOU',
        nomCourt: 'Adhésion Mouvement',
        nomLong: "POST'AIR - Adhésion Mouvement",
        adMapping: 'GT-0412',
      },
      codeER: '006',
      dateReception: '2018-03-01T00:00:00+0000',
      nbTacheEncours: 0,
      numAdhesion: '0002405564',
      idMnt: '11658220',
      isVIP: false,
      affectation: {
        personneAffectee: 'Gestionnaire PGVDC',
        dateAffectation: '2021-03-11T18:04:06+0000',
        equipePersonneAffectee: 6,
      },
      type: {
        id: 28,
        code: 'ADHP',
        nomCourt: 'ADHPREV',
        nomLong: 'Adhésion - Prévoyance',
        categorie: 8,
        readyState: 'À typer',
      },
      origine: {
        id: 2,
        code: 'BDX',
        nomCourt: 'BORDEAUX',
        nomLong: 'Centre de démat - Bordeaux',
      },
      nbTacheTerminee: 4,
      isTestDemande: false,
      statut: 'Amendée',
    },
    {
      categorie: {
        id: 42,
        code: 'DCA',
        nomCourt: 'DCADH',
        nomLong: 'Décès adhérents / Ayant droit',
      },
      motif: { code: 'PAYE', nomLong: 'Payée', isDisplayed: true },
      dateCreation: '2018-03-01T00:00:00+0000',
      numGroupeAssure: '00-PS',
      dateEtat: '2021-02-02T12:32:56+0000',
      id: 36,
      nomAdherent: 'PRICC',
      numInfinite: '15256357',
      isDeletedDemande: false,
      dateScan: '2018-03-01T10:40:20+0000',
      idContrat: '006004-PCL',
      prenomAdherent: 'PIERRE ERIC',
      lotId: 3,
      nbDocuments: 17,
      etat: 'Clôturée',
      equipePersonneAffectee: {
        id: 43,
        code: 'PSSANT',
        nomCourt: 'Presta Santé',
        nomLong: 'Prestation Santé',
        adMapping: 'GT-1366',
      },
      codeER: '006',
      dateReception: '2018-03-01T00:00:00+0000',
      nbTacheEncours: 0,
      numAdhesion: '0002405564',
      idMnt: '11658220',
      isVIP: false,
      affectation: {
        personneAffectee: 'ZINOUNE Rachid',
        dateAffectation: '2021-02-02T12:32:56+0000',
        equipePersonneAffectee: 43,
      },
      type: {
        id: 79,
        code: 'DASP',
        nomCourt: 'DCASP',
        nomLong: 'Décès adhérents / Ayant droit - Décès sans prestation',
        categorie: 42,
        readyState: 'À typer',
      },
      origine: {
        id: 2,
        code: 'BDX',
        nomCourt: 'BORDEAUX',
        nomLong: 'Centre de démat - Bordeaux',
      },
      nbTacheTerminee: 3,
      isTestDemande: false,
      statut: 'Amendée',
    },
    {
      categorie: {
        id: 10,
        code: 'PREV',
        nomCourt: 'PRESTAPREV',
        nomLong: 'Prestation - Prévoyance',
      },
      motif: { code: 'PAYE', nomLong: 'Payée', isDisplayed: true },
      dateCreation: '2018-03-01T13:08:02+0000',
      numGroupeAssure: '00-PS',
      dateEtat: '2021-02-04T12:18:17+0000',
      id: 41,
      nomAdherent: 'PRICCO',
      numInfinite: '15256357',
      isDeletedDemande: false,
      dateScan: '2018-03-01T13:10:12+0000',
      idContrat: '006004-PCL',
      prenomAdherent: 'PIERRE ERIC',
      lotId: 6,
      nbDocuments: 4,
      etat: 'Clôturée',
      equipePersonneAffectee: {
        id: 4,
        code: 'CTPP75',
        nomCourt: "POST'AIR - CTPP 75",
        nomLong: 'Centre de traitement prestations prévoyance 75',
        adMapping: 'GT-0422',
      },
      codeER: '006',
      dateReception: '2018-03-01T00:00:00+0000',
      nbTacheEncours: 0,
      numAdhesion: '0000461477',
      idMnt: '11658220',
      isVIP: false,
      affectation: {
        personneAffectee: 'ZINOUNE Rachid',
        dateAffectation: '2021-02-04T12:18:17+0000',
        equipePersonneAffectee: 4,
      },
      type: {
        id: 78,
        code: 'DECV',
        nomCourt: 'DECERTIVIE',
        nomLong: 'DEPENDANCE - Certificat de vie',
        categorie: 10,
        readyState: 'À typer',
      },
      origine: {
        id: 2,
        code: 'BDX',
        nomCourt: 'BORDEAUX',
        nomLong: 'Centre de démat - Bordeaux',
      },
      nbTacheTerminee: 1,
      isTestDemande: false,
      statut: 'Amendée',
    },
    {
      etat: 'Reçue',
      categorie: {
        id: 10,
        code: 'PREV',
        nomCourt: 'PRESTAPREV',
        nomLong: 'Prestation - Prévoyance',
      },
      dateCreation: '2018-03-01T13:08:01+0000',
      numGroupeAssure: '00-PS',
      dateEtat: '2021-02-04T10:23:11+0000',
      id: 55,
      nomAdherent: 'PRICCO',
      numInfinite: '15256357',
      isDeletedDemande: false,
      dateScan: '2018-03-01T13:10:12+0000',
      type: {
        id: 78,
        code: 'DECV',
        nomCourt: 'DECERTIVIE',
        nomLong: 'DEPENDANCE - Certificat de vie',
        categorie: 10,
        readyState: 'À typer',
      },
      idContrat: '006004-PCL',
      prenomAdherent: 'PIERRE ERIC',
      lotId: 6,
      nbDocuments: 4,
      affectationEquipe: {
        equipe: {
          id: 2,
          code: 'CTPP33',
          nomCourt: "POST'AIR - CTPP 33",
          nomLong: 'Centre de traitement prestations prévoyance 33',
          adMapping: 'GT-0419',
        },
        dateAffectation: '2021-02-15T14:56:10+0000',
      },
      codeER: '006',
      dateReception: '2018-03-01T00:00:00+0000',
      nbTacheEncours: 0,
      numAdhesion: '0002405564',
      idMnt: '11658220',
      isVIP: false,
      origine: {
        id: 2,
        code: 'BDX',
        nomCourt: 'BORDEAUX',
        nomLong: 'Centre de démat - Bordeaux',
      },
      nbTacheTerminee: 2,
      isTestDemande: false,
      statut: 'Amendée',
    },
    {
      categorie: {
        id: 10,
        code: 'PREV',
        nomCourt: 'PRESTAPREV',
        nomLong: 'Prestation - Prévoyance',
      },
      motif: { code: 'CLM', nomLong: 'Clôture en masse', isDisplayed: false },
      dateCreation: '2018-03-01T13:08:02+0000',
      numGroupeAssure: '00-PS',
      dateEtat: '2021-02-11T17:08:24+0000',
      id: 56,
      nomAdherent: 'PRICCO',
      numInfinite: '15256357',
      isDeletedDemande: false,
      dateScan: '2018-03-01T13:10:12+0000',
      idContrat: '006004-PCL',
      prenomAdherent: 'PIERRE ERIC',
      lotId: 6,
      nbDocuments: 7,
      etat: 'Clôturée',
      equipePersonneAffectee: {
        id: 4,
        code: 'CTPP75',
        nomCourt: "POST'AIR - CTPP 75",
        nomLong: 'Centre de traitement prestations prévoyance 75',
        adMapping: 'GT-0422',
      },
      codeER: '006',
      dateReception: '2018-03-01T00:00:00+0000',
      nbTacheEncours: 0,
      numAdhesion: '0000461477',
      idMnt: '11658220',
      isVIP: false,
      affectation: {
        personneAffectee: 'ACHOUR Nora',
        dateAffectation: '2021-02-04T10:23:11+0000',
        equipePersonneAffectee: 4,
      },
      type: {
        id: 52,
        code: 'DCII',
        nomCourt: 'DCIIJ',
        nomLong: "Compléments d'indemnisation",
        categorie: 10,
        readyState: 'À typer',
      },
      origine: {
        id: 2,
        code: 'BDX',
        nomCourt: 'BORDEAUX',
        nomLong: 'Centre de démat - Bordeaux',
      },
      nbTacheTerminee: 1,
      isTestDemande: false,
      statut: 'Amendée',
    },
    {
      categorie: { id: 56, code: 'CSS', nomCourt: 'CSS', nomLong: 'CSS' },
      motif: { code: 'CLM', nomLong: 'Clôture en masse', isDisplayed: false },
      dateCreation: '2018-03-01T00:00:00+0000',
      numGroupeAssure: '00',
      dateEtat: '2021-02-19T08:44:14+0000',
      id: 58,
      nomAdherent: 'KIELBOWICZ',
      numInfinite: '16992124',
      isDeletedDemande: false,
      dateScan: '2018-03-01T13:10:12+0000',
      idContrat: '095424-CMS',
      prenomAdherent: 'CHRISTIAN',
      lotId: 6,
      nbDocuments: 1,
      etat: 'Clôturée',
      equipePersonneAffectee: {
        id: 4,
        code: 'CTPP75',
        nomCourt: "POST'AIR - CTPP 75",
        nomLong: 'Centre de traitement prestations prévoyance 75',
        adMapping: 'GT-0422',
      },
      codeER: '095',
      dateReception: '2018-03-01T00:00:00+0000',
      nbTacheEncours: 0,
      numAdhesion: '0002747914',
      idMnt: '11419231',
      isVIP: false,
      affectation: {
        personneAffectee: 'ACHOUR Nora',
        dateAffectation: '2021-02-04T10:23:11+0000',
        equipePersonneAffectee: 4,
      },
      type: {
        id: 164,
        code: 'ADGS',
        nomCourt: 'ADGS',
        nomLong: 'Acte de gestion',
        categorie: 56,
        readyState: 'À typer',
      },
      origine: {
        id: 2,
        code: 'BDX',
        nomCourt: 'BORDEAUX',
        nomLong: 'Centre de démat - Bordeaux',
      },
      nbTacheTerminee: 1,
      isTestDemande: false,
      statut: 'Nouvelle',
    },
    {
      categorie: {
        id: 2,
        code: 'AMS',
        nomCourt: 'AMS',
        nomLong: 'Adhésions Mouvement Santé',
      },
      motif: { code: 'CLM', nomLong: 'Clôture en masse', isDisplayed: false },
      dateCreation: '2018-03-01T13:08:02+0000',
      numGroupeAssure: '00-PS',
      dateEtat: '2021-02-19T08:44:14+0000',
      id: 61,
      nomAdherent: 'PRICCO',
      numInfinite: '15256357',
      isDeletedDemande: false,
      dateScan: '2018-03-01T13:10:12+0000',
      idContrat: '006004-PCL',
      prenomAdherent: 'PIERRE ERIC',
      lotId: 6,
      nbDocuments: 1,
      etat: 'Clôturée',
      equipePersonneAffectee: {
        id: 4,
        code: 'CTPP75',
        nomCourt: "POST'AIR - CTPP 75",
        nomLong: 'Centre de traitement prestations prévoyance 75',
        adMapping: 'GT-0422',
      },
      codeER: '006',
      dateReception: '2018-03-01T00:00:00+0000',
      nbTacheEncours: 0,
      numAdhesion: '0000461477',
      idMnt: '11658220',
      isVIP: false,
      affectation: {
        personneAffectee: 'ACHOUR Nora',
        dateAffectation: '2021-02-04T10:23:11+0000',
        equipePersonneAffectee: 4,
      },
      type: {
        id: 5,
        code: 'ADHS',
        nomCourt: 'ADHSANTE',
        nomLong: 'Adhésion/réactivation - Santé',
        categorie: 2,
        readyState: 'À typer',
      },
      origine: {
        id: 2,
        code: 'BDX',
        nomCourt: 'BORDEAUX',
        nomLong: 'Centre de démat - Bordeaux',
      },
      nbTacheTerminee: 0,
      isTestDemande: false,
      statut: 'Nouvelle',
    },
    {
      categorie: {
        id: 2,
        code: 'AMS',
        nomCourt: 'AMS',
        nomLong: 'Adhésions Mouvement Santé',
      },
      motif: {
        code: 'INRE',
        nomLong: 'Pour information réseau',
        isDisplayed: true,
      },
      dateCreation: '2018-03-01T13:08:33+0000',
      numGroupeAssure: '00-PS',
      dateEtat: '2021-03-11T18:58:37+0000',
      id: 65,
      nomAdherent: 'PRICCO',
      numInfinite: '15256357',
      isDeletedDemande: false,
      dateScan: '2018-03-01T13:10:12+0000',
      idContrat: '006004-PCL',
      prenomAdherent: 'PIERRE ERIC',
      lotId: 7,
      nbDocuments: 12,
      etat: 'Clôturée',
      equipePersonneAffectee: {
        id: 6,
        code: 'ADHMOU',
        nomCourt: 'Adhésion Mouvement',
        nomLong: "POST'AIR - Adhésion Mouvement",
        adMapping: 'GT-0412',
      },
      codeER: '006',
      dateReception: '2018-03-01T00:00:00+0000',
      nbTacheEncours: 0,
      numAdhesion: '0000461477',
      idMnt: '11658220',
      isVIP: false,
      affectation: {
        personneAffectee: 'postair-user-superviseur',
        dateAffectation: '2021-03-11T18:58:37+0000',
        equipePersonneAffectee: 6,
      },
      type: {
        id: 5,
        code: 'ADHS',
        nomCourt: 'ADHSANTE',
        nomLong: 'Adhésion/réactivation - Santé',
        categorie: 2,
        readyState: 'À typer',
      },
      origine: {
        id: 2,
        code: 'BDX',
        nomCourt: 'BORDEAUX',
        nomLong: 'Centre de démat - Bordeaux',
      },
      nbTacheTerminee: 0,
      isTestDemande: false,
      statut: 'Amendée',
    },
    {
      etat: 'Reçue',
      categorie: {
        id: 2,
        code: 'AMS',
        nomCourt: 'AMS',
        nomLong: 'Adhésions Mouvement Santé',
      },
      dateCreation: '2018-03-01T13:08:33+0000',
      numGroupeAssure: '00-PS',
      dateEtat: '2021-03-17T10:40:39+0000',
      id: 70,
      nomAdherent: 'PRICCO',
      numInfinite: '15256357',
      isDeletedDemande: false,
      dateScan: '2018-03-01T13:10:12+0000',
      type: {
        id: 5,
        code: 'ADHS',
        nomCourt: 'ADHSANTE',
        nomLong: 'Adhésion/réactivation - Santé',
        categorie: 2,
        readyState: 'À typer',
      },
      idContrat: '006004-PCL',
      prenomAdherent: 'PIERRE ERIC',
      lotId: 7,
      nbDocuments: 1,
      affectationEquipe: {
        equipe: {
          id: 8,
          code: 'BDX',
          nomCourt: 'BDX',
          nomLong: "POST'AIR - Pôle courrier Bordeaux",
          adMapping: 'GT-0414',
        },
        dateAffectation: '2021-03-17T10:40:39+0000',
      },
      codeER: '006',
      dateReception: '2018-03-01T00:00:00+0000',
      nbTacheEncours: 0,
      numAdhesion: '0002405564',
      idMnt: '11658220',
      isVIP: false,
      origine: {
        id: 2,
        code: 'BDX',
        nomCourt: 'BORDEAUX',
        nomLong: 'Centre de démat - Bordeaux',
      },
      nbTacheTerminee: 0,
      isTestDemande: false,
      statut: 'Amendée',
    },
    {
      categorie: { id: 55, code: 'CTC', nomCourt: 'CTC', nomLong: 'CTC' },
      motif: { code: 'SASU', nomLong: 'Sans suite', isDisplayed: true },
      dateCreation: '2018-03-01T00:00:00+0000',
      numGroupeAssure: '00-PS',
      dateEtat: '2021-03-11T18:59:19+0000',
      id: 83,
      nomAdherent: 'ROY',
      isDeletedDemande: false,
      dateScan: '2018-03-01T13:13:12+0000',
      idContrat: '003185-PCL',
      prenomAdherent: 'SEVERINE',
      lotId: 8,
      nbDocuments: 9,
      etat: 'Clôturée',
      equipePersonneAffectee: {
        id: 4,
        code: 'CTPP75',
        nomCourt: "POST'AIR - CTPP 75",
        nomLong: 'Centre de traitement prestations prévoyance 75',
        adMapping: 'GT-0422',
      },
      codeER: '002',
      dateReception: '2018-03-01T00:00:00+0000',
      nbTacheEncours: 0,
      numAdhesion: '0003134447',
      idMnt: '17387565',
      isVIP: false,
      affectation: {
        personneAffectee: 'postair-user-superviseur',
        dateAffectation: '2021-03-11T18:59:19+0000',
        equipePersonneAffectee: 4,
      },
      type: {
        id: 202,
        code: 'CRRA',
        nomCourt: 'RC-RADIAT',
        nomLong: 'Remboursement de cotisations - Radiation',
        categorie: 55,
        readyState: 'À typer',
      },
      origine: {
        id: 2,
        code: 'BDX',
        nomCourt: 'BORDEAUX',
        nomLong: 'Centre de démat - Bordeaux',
      },
      nbTacheTerminee: 1,
      isTestDemande: false,
      statut: 'Amendée',
    },
    {
      categorie: {
        id: 2,
        code: 'AMS',
        nomCourt: 'AMS',
        nomLong: 'Adhésions Mouvement Santé',
      },
      motif: { code: 'CLM', nomLong: 'Clôture en masse', isDisplayed: false },
      dateCreation: '2018-03-01T13:11:04+0000',
      numGroupeAssure: '00-PS',
      dateEtat: '2021-02-19T08:44:14+0000',
      id: 91,
      nomAdherent: 'PRICCO',
      numInfinite: '15256357',
      isDeletedDemande: false,
      dateScan: '2018-03-01T13:13:12+0000',
      idContrat: '006004-PCL',
      prenomAdherent: 'PIERRE ERIC',
      lotId: 8,
      nbDocuments: 3,
      etat: 'Clôturée',
      equipePersonneAffectee: {
        id: 4,
        code: 'CTPP75',
        nomCourt: "POST'AIR - CTPP 75",
        nomLong: 'Centre de traitement prestations prévoyance 75',
        adMapping: 'GT-0422',
      },
      codeER: '006',
      dateReception: '2018-03-01T00:00:00+0000',
      nbTacheEncours: 0,
      numAdhesion: '0000461477',
      idMnt: '11658220',
      isVIP: false,
      affectation: {
        personneAffectee: 'ACHOUR Nora',
        dateAffectation: '2021-02-04T10:23:11+0000',
        equipePersonneAffectee: 4,
      },
      type: {
        id: 5,
        code: 'ADHS',
        nomCourt: 'ADHSANTE',
        nomLong: 'Adhésion/réactivation - Santé',
        categorie: 2,
        readyState: 'À typer',
      },
      origine: {
        id: 2,
        code: 'BDX',
        nomCourt: 'BORDEAUX',
        nomLong: 'Centre de démat - Bordeaux',
      },
      nbTacheTerminee: 0,
      isTestDemande: false,
      statut: 'Nouvelle',
    },
    {
      categorie: { id: 56, code: 'CSS', nomCourt: 'CSS', nomLong: 'CSS' },
      motif: { code: 'CLM', nomLong: 'Clôture en masse', isDisplayed: false },
      dateCreation: '2018-03-01T13:11:03+0000',
      numGroupeAssure: '00-PS',
      dateEtat: '2021-02-19T08:44:14+0000',
      id: 96,
      nomAdherent: 'PRICCO',
      numInfinite: '15256357',
      isDeletedDemande: false,
      dateScan: '2018-03-01T13:13:12+0000',
      idContrat: '006004-PCL',
      prenomAdherent: 'PIERRE ERIC',
      lotId: 8,
      nbDocuments: 3,
      etat: 'Clôturée',
      equipePersonneAffectee: {
        id: 4,
        code: 'CTPP75',
        nomCourt: "POST'AIR - CTPP 75",
        nomLong: 'Centre de traitement prestations prévoyance 75',
        adMapping: 'GT-0422',
      },
      codeER: '006',
      dateReception: '2018-03-01T00:00:00+0000',
      nbTacheEncours: 0,
      numAdhesion: '0000461477',
      idMnt: '11658220',
      isVIP: false,
      affectation: {
        personneAffectee: 'ACHOUR Nora',
        dateAffectation: '2021-02-04T10:23:11+0000',
        equipePersonneAffectee: 4,
      },
      type: {
        id: 212,
        code: 'ADHN',
        nomCourt: 'ADHN',
        nomLong: 'Adhésion avec participation non-territoriaux',
        categorie: 56,
        readyState: 'À typer',
      },
      origine: {
        id: 2,
        code: 'BDX',
        nomCourt: 'BORDEAUX',
        nomLong: 'Centre de démat - Bordeaux',
      },
      nbTacheTerminee: 0,
      isTestDemande: false,
      statut: 'Nouvelle',
    },
    {
      categorie: {
        id: 10,
        code: 'PREV',
        nomCourt: 'PRESTAPREV',
        nomLong: 'Prestation - Prévoyance',
      },
      motif: { code: 'CLM', nomLong: 'Clôture en masse', isDisplayed: false },
      dateCreation: '2018-03-01T13:11:04+0000',
      numGroupeAssure: '00-PS',
      dateEtat: '2021-02-19T08:44:14+0000',
      id: 98,
      nomAdherent: 'PRICCO',
      numInfinite: '15256357',
      isDeletedDemande: false,
      dateScan: '2018-03-01T13:13:12+0000',
      idContrat: '006004-PCL',
      prenomAdherent: 'PIERRE ERIC',
      lotId: 8,
      nbDocuments: 4,
      etat: 'Clôturée',
      equipePersonneAffectee: {
        id: 4,
        code: 'CTPP75',
        nomCourt: "POST'AIR - CTPP 75",
        nomLong: 'Centre de traitement prestations prévoyance 75',
        adMapping: 'GT-0422',
      },
      codeER: '006',
      dateReception: '2018-03-01T00:00:00+0000',
      nbTacheEncours: 0,
      numAdhesion: '0000461477',
      idMnt: '11658220',
      isVIP: false,
      affectation: {
        personneAffectee: 'ACHOUR Nora',
        dateAffectation: '2021-02-04T10:23:11+0000',
        equipePersonneAffectee: 4,
      },
      type: {
        id: 92,
        code: 'INIJ',
        nomCourt: 'INDIJ',
        nomLong: 'Indus - Indemnités journalières',
        categorie: 10,
        readyState: 'Reçue',
      },
      origine: {
        id: 2,
        code: 'BDX',
        nomCourt: 'BORDEAUX',
        nomLong: 'Centre de démat - Bordeaux',
      },
      nbTacheTerminee: 0,
      isTestDemande: false,
      statut: 'Amendée',
    },
    {
      categorie: {
        id: 10,
        code: 'PREV',
        nomCourt: 'PRESTAPREV',
        nomLong: 'Prestation - Prévoyance',
      },
      motif: { code: 'CLM', nomLong: 'Clôture en masse', isDisplayed: false },
      dateCreation: '2018-03-01T13:15:04+0000',
      numGroupeAssure: '00-PS',
      dateEtat: '2021-02-19T08:44:33+0000',
      id: 100,
      nomAdherent: 'CLEUVENOT',
      isDeletedDemande: false,
      dateScan: '2018-03-01T13:18:12+0000',
      idContrat: '088114-PCL',
      prenomAdherent: 'PHILIPPE',
      lotId: 9,
      nbDocuments: 2,
      etat: 'Clôturée',
      equipePersonneAffectee: {
        id: 4,
        code: 'CTPP75',
        nomCourt: "POST'AIR - CTPP 75",
        nomLong: 'Centre de traitement prestations prévoyance 75',
        adMapping: 'GT-0422',
      },
      codeER: '002',
      dateReception: '2018-03-01T00:00:00+0000',
      nbTacheEncours: 0,
      numAdhesion: '0003136195',
      isVIP: false,
      affectation: {
        personneAffectee: 'ACHOUR Nora',
        dateAffectation: '2021-02-04T10:23:11+0000',
        equipePersonneAffectee: 4,
      },
      type: {
        id: 78,
        code: 'DECV',
        nomCourt: 'DECERTIVIE',
        nomLong: 'DEPENDANCE - Certificat de vie',
        categorie: 10,
        readyState: 'À typer',
      },
      origine: {
        id: 2,
        code: 'BDX',
        nomCourt: 'BORDEAUX',
        nomLong: 'Centre de démat - Bordeaux',
      },
      nbTacheTerminee: 0,
      isTestDemande: false,
      statut: 'Nouvelle',
    },
    {
      categorie: {
        id: 10,
        code: 'PREV',
        nomCourt: 'PRESTAPREV',
        nomLong: 'Prestation - Prévoyance',
      },
      motif: { code: 'CLM', nomLong: 'Clôture en masse', isDisplayed: false },
      dateCreation: '2018-03-01T13:15:04+0000',
      numGroupeAssure: '00-PS',
      dateEtat: '2021-02-19T08:44:33+0000',
      id: 101,
      nomAdherent: 'PRICCO',
      numInfinite: '15256357',
      isDeletedDemande: false,
      dateScan: '2018-03-01T13:18:12+0000',
      idContrat: '006004-PCL',
      prenomAdherent: 'PIERRE ERIC',
      lotId: 9,
      nbDocuments: 2,
      etat: 'Clôturée',
      equipePersonneAffectee: {
        id: 4,
        code: 'CTPP75',
        nomCourt: "POST'AIR - CTPP 75",
        nomLong: 'Centre de traitement prestations prévoyance 75',
        adMapping: 'GT-0422',
      },
      codeER: '006',
      dateReception: '2018-03-01T00:00:00+0000',
      nbTacheEncours: 0,
      numAdhesion: '0000461477',
      idMnt: '11658220',
      isVIP: false,
      affectation: {
        personneAffectee: 'ACHOUR Nora',
        dateAffectation: '2021-02-04T10:23:11+0000',
        equipePersonneAffectee: 4,
      },
      type: {
        id: 78,
        code: 'DECV',
        nomCourt: 'DECERTIVIE',
        nomLong: 'DEPENDANCE - Certificat de vie',
        categorie: 10,
        readyState: 'À typer',
      },
      origine: {
        id: 2,
        code: 'BDX',
        nomCourt: 'BORDEAUX',
        nomLong: 'Centre de démat - Bordeaux',
      },
      nbTacheTerminee: 0,
      isTestDemande: false,
      statut: 'Nouvelle',
    },
    {
      categorie: {
        id: 8,
        code: 'AMP',
        nomCourt: 'AMP',
        nomLong: 'Adhésions Mouvement Prévoyance',
      },
      dateCreation: '2018-03-01T13:15:34+0000',
      numGroupeAssure: '00-PS',
      dateEtat: '2021-02-04T10:23:11+0000',
      id: 104,
      nomAdherent: 'PRICCO',
      numInfinite: '15256357',
      isDeletedDemande: false,
      dateScan: '2018-03-01T13:18:12+0000',
      idContrat: '006004-PCL',
      prenomAdherent: 'PIERRE ERIC',
      lotId: 9,
      nbDocuments: 330,
      etat: 'Affectée',
      equipePersonneAffectee: {
        id: 4,
        code: 'CTPP75',
        nomCourt: "POST'AIR - CTPP 75",
        nomLong: 'Centre de traitement prestations prévoyance 75',
        adMapping: 'GT-0422',
      },
      codeER: '006',
      dateReception: '2018-03-01T00:00:00+0000',
      nbTacheEncours: 0,
      numAdhesion: '0000461477',
      idMnt: '11658220',
      isVIP: false,
      affectation: {
        personneAffectee: 'ACHOUR Nora',
        dateAffectation: '2021-02-04T10:23:11+0000',
        equipePersonneAffectee: 4,
      },
      type: {
        id: 28,
        code: 'ADHP',
        nomCourt: 'ADHPREV',
        nomLong: 'Adhésion - Prévoyance',
        categorie: 8,
        readyState: 'À typer',
      },
      origine: {
        id: 2,
        code: 'BDX',
        nomCourt: 'BORDEAUX',
        nomLong: 'Centre de démat - Bordeaux',
      },
      nbTacheTerminee: 1,
      isTestDemande: false,
      statut: 'Amendée',
    },
    {
      categorie: {
        id: 10,
        code: 'PREV',
        nomCourt: 'PRESTAPREV',
        nomLong: 'Prestation - Prévoyance',
      },
      dateCreation: '2018-03-01T13:19:05+0000',
      numGroupeAssure: '00-PS',
      dateEtat: '2021-02-04T10:23:11+0000',
      id: 120,
      nomAdherent: 'PRICCO',
      numInfinite: '15256357',
      isDeletedDemande: false,
      dateScan: '2018-03-01T13:22:12+0000',
      idContrat: '006004-PCL',
      prenomAdherent: 'PIERRE ERIC',
      lotId: 10,
      nbDocuments: 1,
      etat: 'Affectée',
      equipePersonneAffectee: {
        id: 4,
        code: 'CTPP75',
        nomCourt: "POST'AIR - CTPP 75",
        nomLong: 'Centre de traitement prestations prévoyance 75',
        adMapping: 'GT-0422',
      },
      codeER: '006',
      dateReception: '2018-03-01T00:00:00+0000',
      nbTacheEncours: 0,
      numAdhesion: '0000461477',
      idMnt: '11658220',
      isVIP: false,
      affectation: {
        personneAffectee: 'ACHOUR Nora',
        dateAffectation: '2021-02-04T10:23:11+0000',
        equipePersonneAffectee: 4,
      },
      type: {
        id: 51,
        code: 'DODI',
        nomCourt: 'DODIJ',
        nomLong: 'Ouverture de droits',
        categorie: 10,
        readyState: 'À typer',
      },
      origine: {
        id: 2,
        code: 'BDX',
        nomCourt: 'BORDEAUX',
        nomLong: 'Centre de démat - Bordeaux',
      },
      nbTacheTerminee: 0,
      isTestDemande: false,
      statut: 'Nouvelle',
    },
    {
      categorie: { id: 55, code: 'CTC', nomCourt: 'CTC', nomLong: 'CTC' },
      dateCreation: '2018-03-01T00:00:00+0000',
      numGroupeAssure: '00-PS',
      dateEtat: '2021-02-04T10:23:11+0000',
      id: 133,
      nomAdherent: 'PRICCO',
      numInfinite: '15256357',
      isDeletedDemande: false,
      dateScan: '2018-03-01T13:23:12+0000',
      idContrat: '006004-PCL',
      prenomAdherent: 'PIERRE ERIC',
      lotId: 11,
      nbDocuments: 1,
      etat: 'Affectée',
      equipePersonneAffectee: {
        id: 4,
        code: 'CTPP75',
        nomCourt: "POST'AIR - CTPP 75",
        nomLong: 'Centre de traitement prestations prévoyance 75',
        adMapping: 'GT-0422',
      },
      codeER: '006',
      dateReception: '2018-03-01T00:00:00+0000',
      nbTacheEncours: 0,
      numAdhesion: '0000461477',
      idMnt: '11658220',
      isVIP: false,
      affectation: {
        personneAffectee: 'ACHOUR Nora',
        dateAffectation: '2021-02-04T10:23:11+0000',
        equipePersonneAffectee: 4,
      },
      type: {
        id: 204,
        code: 'CRMU',
        nomCourt: 'RC-MUT',
        nomLong: 'Remboursement de cotisations - Mutation',
        categorie: 55,
        readyState: 'À typer',
      },
      origine: {
        id: 2,
        code: 'BDX',
        nomCourt: 'BORDEAUX',
        nomLong: 'Centre de démat - Bordeaux',
      },
      nbTacheTerminee: 0,
      isTestDemande: false,
      statut: 'Nouvelle',
    },
    {
      categorie: {
        id: 2,
        code: 'AMS',
        nomCourt: 'AMS',
        nomLong: 'Adhésions Mouvement Santé',
      },
      dateCreation: '2018-03-01T13:20:35+0000',
      numGroupeAssure: '00-PS',
      dateEtat: '2021-02-04T10:23:11+0000',
      id: 135,
      nomAdherent: 'PRICCO',
      numInfinite: '15256357',
      isDeletedDemande: false,
      dateScan: '2018-03-01T13:23:12+0000',
      idContrat: '006004-PCL',
      prenomAdherent: 'PIERRE ERIC',
      lotId: 11,
      nbDocuments: 3,
      etat: 'Affectée',
      equipePersonneAffectee: {
        id: 4,
        code: 'CTPP75',
        nomCourt: "POST'AIR - CTPP 75",
        nomLong: 'Centre de traitement prestations prévoyance 75',
        adMapping: 'GT-0422',
      },
      codeER: '006',
      dateReception: '2018-03-01T00:00:00+0000',
      nbTacheEncours: 0,
      numAdhesion: '0000461477',
      idMnt: '11658220',
      isVIP: false,
      affectation: {
        personneAffectee: 'ACHOUR Nora',
        dateAffectation: '2021-02-04T10:23:11+0000',
        equipePersonneAffectee: 4,
      },
      type: {
        id: 5,
        code: 'ADHS',
        nomCourt: 'ADHSANTE',
        nomLong: 'Adhésion/réactivation - Santé',
        categorie: 2,
        readyState: 'À typer',
      },
      origine: {
        id: 2,
        code: 'BDX',
        nomCourt: 'BORDEAUX',
        nomLong: 'Centre de démat - Bordeaux',
      },
      nbTacheTerminee: 1,
      isTestDemande: false,
      statut: 'Nouvelle',
    },
    {
      categorie: {
        id: 10,
        code: 'PREV',
        nomCourt: 'PRESTAPREV',
        nomLong: 'Prestation - Prévoyance',
      },
      motif: { code: 'PAYE', nomLong: 'Payée', isDisplayed: true },
      dateCreation: '2018-03-01T14:19:15+0000',
      numGroupeAssure: 'RET',
      dateEtat: '2021-02-04T17:34:05+0000',
      id: 286,
      nomAdherent: 'FOUQUET',
      numInfinite: '2161401',
      isDeletedDemande: false,
      dateScan: '2018-03-01T14:21:14+0000',
      idContrat: '078IND-CMS',
      prenomAdherent: 'THERESE',
      lotId: 22,
      nbDocuments: 1,
      etat: 'Clôturée',
      equipePersonneAffectee: {
        id: 2,
        code: 'CTPP33',
        nomCourt: "POST'AIR - CTPP 33",
        nomLong: 'Centre de traitement prestations prévoyance 33',
        adMapping: 'GT-0419',
      },
      codeER: '078',
      dateReception: '2018-03-01T00:00:00+0000',
      nbTacheEncours: 0,
      numAdhesion: '0000040756',
      idMnt: '12015892',
      isVIP: false,
      affectation: {
        personneAffectee: 'postair-user-gestionnaire9',
        dateAffectation: '2019-09-09T12:17:03+0000',
        equipePersonneAffectee: 2,
      },
      type: {
        id: 78,
        code: 'DECV',
        nomCourt: 'DECERTIVIE',
        nomLong: 'DEPENDANCE - Certificat de vie',
        categorie: 10,
        readyState: 'À typer',
      },
      origine: {
        id: 2,
        code: 'BDX',
        nomCourt: 'BORDEAUX',
        nomLong: 'Centre de démat - Bordeaux',
      },
      nbTacheTerminee: 0,
      isTestDemande: false,
      statut: 'Nouvelle',
    },
    {
      categorie: {
        id: 10,
        code: 'PREV',
        nomCourt: 'PRESTAPREV',
        nomLong: 'Prestation - Prévoyance',
      },
      idContrat: '078IND-CMS',
      prenomAdherent: 'THERESE',
      lotId: 22,
      nbDocuments: 2,
      etat: 'En attente',
      equipePersonneAffectee: {
        id: 2,
        code: 'CTPP33',
        nomCourt: "POST'AIR - CTPP 33",
        nomLong: 'Centre de traitement prestations prévoyance 33',
        adMapping: 'GT-0419',
      },
      codeER: '078',
      dateReception: '2018-03-01T00:00:00+0000',
      nbTacheEncours: 1,
      numAdhesion: '0000040756',
      idMnt: '12015892',
      isVIP: false,
      affectation: {
        personneAffectee: 'postair-user-gestionnaire9',
        dateAffectation: '2021-02-08T11:42:20+0000',
        equipePersonneAffectee: 2,
      },
      type: {
        id: 78,
        code: 'DECV',
        nomCourt: 'DECERTIVIE',
        nomLong: 'DEPENDANCE - Certificat de vie',
        categorie: 10,
        readyState: 'À typer',
      },
      origine: {
        id: 2,
        code: 'BDX',
        nomCourt: 'BORDEAUX',
        nomLong: 'Centre de démat - Bordeaux',
      },
      nbTacheTerminee: 0,
      isTestDemande: false,
      statut: 'Amendée',
    },
    {
      categorie: {
        id: 10,
        code: 'PREV',
        nomCourt: 'PRESTAPREV',
        nomLong: 'Prestation - Prévoyance',
      },
      motif: { code: 'PAYE', nomLong: 'Payée', isDisplayed: true },
      dateCreation: '2018-03-01T14:19:18+0000',
      numGroupeAssure: 'RET',
      dateEtat: '2021-02-08T14:44:06+0000',
      id: 299,
      nomAdherent: 'FOUQUET',
      numInfinite: '2161401',
      isDeletedDemande: false,
      dateScan: '2018-03-01T14:21:14+0000',
      idContrat: '078IND-CMS',
      prenomAdherent: 'THERESE',
      lotId: 22,
      nbDocuments: 3,
      etat: 'Clôturée',
      equipePersonneAffectee: {
        id: 2,
        code: 'CTPP33',
        nomCourt: "POST'AIR - CTPP 33",
        nomLong: 'Centre de traitement prestations prévoyance 33',
        adMapping: 'GT-0419',
      },
      codeER: '078',
      dateReception: '2018-03-01T00:00:00+0000',
      nbTacheEncours: 0,
      numAdhesion: '0000040756',
      idMnt: '12015892',
      isVIP: false,
      affectation: {
        personneAffectee: 'postair-user-gestionnaire9',
        dateAffectation: '2019-09-09T12:17:03+0000',
        equipePersonneAffectee: 2,
      },
      type: {
        id: 78,
        code: 'DECV',
        nomCourt: 'DECERTIVIE',
        nomLong: 'DEPENDANCE - Certificat de vie',
        categorie: 10,
        readyState: 'À typer',
      },
      origine: {
        id: 2,
        code: 'BDX',
        nomCourt: 'BORDEAUX',
        nomLong: 'Centre de démat - Bordeaux',
      },
      nbTacheTerminee: 0,
      isTestDemande: false,
      statut: 'Amendée',
    },
    {
      categorie: {
        id: 10,
        code: 'PREV',
        nomCourt: 'PRESTAPREV',
        nomLong: 'Prestation - Prévoyance',
      },
      motif: { code: 'PAYE', nomLong: 'Payée', isDisplayed: true },
      dateCreation: '2018-03-01T14:19:19+0000',
      numGroupeAssure: '20-PS',
      dateEtat: '2021-02-08T12:33:48+0000',
      id: 301,
      nomAdherent: 'DUTILH',
      numInfinite: '16475983',
      isDeletedDemande: false,
      dateScan: '2018-03-01T14:21:14+0000',
      idContrat: '033352-PCL',
      prenomAdherent: 'SANDRA',
      lotId: 22,
      nbDocuments: 1,
      etat: 'Clôturée',
      equipePersonneAffectee: {
        id: 2,
        code: 'CTPP33',
        nomCourt: "POST'AIR - CTPP 33",
        nomLong: 'Centre de traitement prestations prévoyance 33',
        adMapping: 'GT-0419',
      },
      codeER: '002',
      dateReception: '2018-03-01T00:00:00+0000',
      nbTacheEncours: 0,
      numAdhesion: '0002746976',
      isVIP: false,
      affectation: {
        personneAffectee: 'postair-user-gestionnaire9',
        dateAffectation: '2019-09-09T12:17:03+0000',
        equipePersonneAffectee: 2,
      },
      type: {
        id: 78,
        code: 'DECV',
        nomCourt: 'DECERTIVIE',
        nomLong: 'DEPENDANCE - Certificat de vie',
        categorie: 10,
        readyState: 'À typer',
      },
      origine: {
        id: 2,
        code: 'BDX',
        nomCourt: 'BORDEAUX',
        nomLong: 'Centre de démat - Bordeaux',
      },
      nbTacheTerminee: 0,
      isTestDemande: false,
      statut: 'Nouvelle',
    },
    {
      description: 'hhh',
      categorie: {
        id: 10,
        code: 'PREV',
        nomCourt: 'PRESTAPREV',
        nomLong: 'Prestation - Prévoyance',
      },
      dateCreation: '2021-01-11T15:59:43+0000',
      numGroupeAssure: '00-IND',
      dateEtat: '2021-02-04T10:23:11+0000',
      id: 1069841,
      nomAdherent: 'CHARLIN',
      isDeletedDemande: false,
      dateScan: '2021-01-11T15:59:43+0000',
      idContrat: '021425-CMS',
      prenomAdherent: 'MICHEL',
      lotId: 120215,
      nbDocuments: 1,
      etat: 'Affectée',
      equipePersonneAffectee: {
        id: 4,
        code: 'CTPP75',
        nomCourt: "POST'AIR - CTPP 75",
        nomLong: 'Centre de traitement prestations prévoyance 75',
        adMapping: 'GT-0422',
      },
      codeER: '002',
      dateReception: '2018-03-01T00:00:00+0000',
      nbTacheEncours: 0,
      idMnt: '00031344',
      isVIP: false,
      affectation: {
        personneAffectee: 'ACHOUR Nora',
        dateAffectation: '2021-02-04T10:23:11+0000',
        equipePersonneAffectee: 4,
      },
      type: {
        id: 78,
        code: 'DECV',
        nomCourt: 'DECERTIVIE',
        nomLong: 'DEPENDANCE - Certificat de vie',
        categorie: 10,
        readyState: 'À typer',
      },
      origine: {
        id: 4,
        code: 'PST',
        nomCourt: 'POSTAIR',
        nomLong: "Gestionnaire - Post'Air",
      },
      nbTacheTerminee: 0,
      isTestDemande: false,
      statut: 'Nouvelle',
    },
  ],
};

const Type = {
  key: 'type',
  children: {
    nomCourt: 'shortName',
    nomLong: 'longName',
    categorie: 'category',
  },
};

const CategoriesWithTypes = {
  key: 'categoriesWithTypes',
  children: {
    nomCourt: 'shortName',
    nomLong: 'longName',
    types: {
      key: 'types',
      children: Type.children,
    },
  },
};

const Category = {
  key: 'category',
  children: {
    nomCourt: 'shortName',
    nomLong: 'longName',
  },
};

const Origin = {
  key: 'origin',
  children: {
    nomCourt: 'shortName',
    nomLong: 'longName',
  },
};

const Assignment = {
  key: 'assignment',
  children: {
    personneAffectee: 'person',
    dateAffectation: 'date',
  },
};

const TeamDemand = {
  key: 'team',
  children: {
    codeERs: 'erCodes',
    nomCourt: 'shortName',
    nomLong: 'longName',
  },
};

const AssignmentTeam = {
  key: 'assignmentTeam',
  children: TeamDemand.children,
};

const AssignmentTeamDemand = {
  key: 'assignmentTeam',
  children: {
    dateAffectation: 'date',
    equipe: TeamDemand,
  },
};

const Reason = {
  key: 'reason',
  children: {
    nomLong: 'longName',
  },
};

const ReasonsByState = {
  key: 'reasons',
  children: Reason.children,
};

const Session = {
  key: 'session',
  children: {
    sessionAuthor: 'author',
    sessionUpdatedAt: 'updatedAt',
    sessionCreatedAt: 'createdAt',
  },
};

const dictionary = {
  demand: {
    origine: Origin,
    categorie: Category,
    type: Type,
    dateReception: 'receiptDate',
    dateCreation: 'createdDate',
    dateScan: 'scanDate',
    etat: 'state',
    motif: Reason,
    dateEtat: 'stateDate',
    prenomAdherent: 'firstName',
    nomAdherent: 'lastName',
    idMnt: 'mntId',
    idContrat: 'collectiveContractId',
    numGroupeAssure: 'insuredGroupId',
    numAdhesion: 'subscriptionId',
    statut: 'status',
    affectation: Assignment,
    affectationEquipe: AssignmentTeamDemand,
    numInfinite: 'infiniteId',
    codeER: 'erCode',
    lotId: 'demandsBatchId',
    nbTacheEncours: 'nbOfTaskInProgress',
    nbTacheTerminee: 'nbOfTaskCompleted',
    numeroFiness: 'professionalHealthId',
    raisonSociale: 'businessName',
    session: Session,
  },
  demandRequest: {
    idMnt: 'mntId',
    numAdhesion: 'subscriptionId',
    'origine.code': 'origin',
    idContrat: 'collectiveContractId',
    prenomAdherent_like: 'firstName',
    numGroupeAssure: 'insuredGroupId',
    'etat.nom': 'state',
    dateReception_to: 'receiptDateTo',
    dateReception_from: 'receiptDateFrom',
    dateEtat_to: 'stateDateTo',
    dateEtat_from: 'stateDateFrom',
    nomAdherent_like: 'lastName',
  },
};

const demand = {
  origine: {
    nomCourt: 'BDX',
    nomLong: 'Centre de Bordeaux',
  },
  dateReception: '2020-01-01',
  dateScan: '2020-01-01',
  etat: 'inProgress',
  dateEtat: '2020-01-01',
  prenomAdherent: 'John',
  nomAdherent: 'DOE',
  idMnt: '1122334455',
  idContrat: '006004-PCL',
  numGroupeAssure: '00-PS',
  numAdhesion: '0000461477',
};

const demandRequest = {
  mntId: '1122334455',
  subscriptionId: '0000461477',
  origin: 'BDX',
  collectiveContractId: '006004-PCL',
};

const Mapper = new MapKeysByDictionary(dictionary);

/*
console.time('test1');
console.log(Mapper.transform(demand, 'demand'));
console.timeEnd('test1');

console.time('test2');
console.log(Mapper.inverseTransform(demandRequest, 'demandRequest'));
console.timeEnd('test2');
*/
const modelConnection = ({ offset = 0, limit = 10, rawData }) => {
  if (!rawData || typeof rawData !== 'object') {
    throw new Error('Raw data should be an object');
  }

  const { items, totalCount } = rawData;

  if (!items) {
    throw new Error(
      'Invalid raw data, it should contain items and totalCount to be modelized into connection'
    );
  }

  const nextOffset = offset + limit;
  const pageInfo = {
    nextOffset,
    hasPreviousPage: offset > 0,
    hasNextPage: nextOffset < totalCount,
  };

  // const edges = [];
  // for (let i = 0; i < items.length - 1; i++) {
  //   edges.push({
  //     node: Mapper.transform(items[i], 'demand'),
  //   });
  // }
  // return {
  //   totalCount,
  //   pageInfo,
  //   edges,
  // };

  return {
    totalCount,
    pageInfo,
    edges: items.map((item) => ({
      node: Mapper.transform(item, 'demand'),
    })),
  };
};

const startTime = performance.now();

modelConnection({ offset: 0, limit: 25, rawData: demandsData }); // <---- The function you're measuring time for

const endTime = performance.now();
console.log(`Call modelConnection took  ${endTime - startTime} milliseconds.`);
